Mission9__stevenf4/Components/CartSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Mission9__stevenf4.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
namespace Mission9__stevenf4.Components

//Receiving the cart object as a constructor argument
{
    public class CartSummaryViewComponent : ViewComponent
    {
        private ShoppingCart cart;
        public CartSummaryViewComponent(ShoppingCart cartService)
        {
            cart = cartService;
        }
        public IViewComponentResult Invoke()
        {
            return View(cart);
        }
    }
}

Mission9__stevenf4/Components/TypesViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Mission9__stevenf4.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Mission9__stevenf4.Components
{
    public class TypesViewComponent : ViewComponent
    {
        private IBookRepository repo { get; set; }

        public TypesViewComponent(IBookRepository temp)
        {
            repo = temp;
        }

        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedType = RouteData?.Values["category"];

            var types = repo.Books
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x);

            return View(types);
        }
    }
}

Mission9__stevenf4/Views/Shared/BookSummary.cshtml
@{
}

@model Book

<div class="card card-outline-primary m-1 p-1">
    <div class="bg-faded p-1">
        <h4>
            @Model.Title

            <span class="badge badge-pill badge-primary" style="float:right">
                <small>@Model.Price.ToString("c")</small>
            </span>
        </h4>
    </div>
    <div class="card-text p-1">@Model.Author</div>
    <div class="card-text p-1">@Model.Publisher</div>v
    <div class="card-text p-1">@Model.Isbn</div>
    <div class="card-text p-1">@Model.Classification</div>
    <div class="card-text p-1">@Model.Category</div>
    <div class="card-text p-1">@Model.PageCount</div>

    <form method="post" asp-page="/Cart">

        <input type="hidden" asp-for="@Model.BookId" />
        <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />

        <span class="card-text">
            <button type="submit" class="btn btn-success btn-sm float-end">Add to Cart</button>
        </span>
    </form>

</div>

Mission9__stevenf4/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
@*<head>
        <meta name="viewport" content="width=device-width" />
        <title>@ViewBag.Title</title>
    </head>
    <body>
        <div>
            @RenderBody()
        </div>
    </body>*@

<head>
    <meta name="viewport" content="width=device-width" />
    <title>Bookstore</title>
    @*<link href="/lib/twitter-bootstrap/bootstrap.min.css" rel="stylesheet" />*@
    @*<link href="C:\Users\stevenfletcher\source\repos\Mission9__stevenf4\Mission9__stevenf4\lib\twitter-bootstrap\bootstrap.min.css" rel="stylesheet" />*@
    @*<link href="C:\Users\stevenfletcher\source\repos\Mission9__stevenf4\Mission9__stevenf4\lib\twitter-bootstrap\css\bootstrap.min.css" rel="stylesheet" />*@
    <link href="/lib/twitter-bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    @*Library for the cart icon*@
    <link href="/lib/font-awesome/css/all.min.css" rel="stylesheet" />
</head>

@*Cart Icon*@
<body>
    <div class="bg-dark text-white p-2">
        <div class="container-fluid">
            <div class="row">
                <div class="col navbar-brand">Bookstore</div>
                <div class="col-6 text-right">
                    <vc:cart-summary />
                </div>
            </div>
        </div>
    </div>
    @*navbar*@
    <div class="bg-dark text-white p-2">
        <span class="navbar-brand ml-2"></span>
    </div>

    <div class="row m-1 p-1">
        <div id="categories" class="col-3">
            <vc:types></vc:types>
        </div>
        <div class="col-9">
            @RenderBody()
        </div>
    </div>
</body>
</html>